### ISSUE TITLE
dump_data in auth/ and world with pysghck

### ISSUE THREAD

**Issue by nlilja** [Shgck/DuratorEmu#1]
Had to fix.. from pysghck dump_data to get_data_dump

Python3.6

**Comment by dece** [comment]
Thanks for reporting. You should instead use the last version of PyShgck updated before I stopped working on DuratorEmu, which is at this ref: https://github.com/Dece/PyShgck/tree/8d457db3e71ebf737d3f8b70f34e576bf8ec234d .

I know I should have used tags or something to pin adequate versions...
