### ISSUE TITLE
Hello, do you have a WoW 1.1.2.4125 version of the client?

### ISSUE THREAD

**Issue by ghost** [Shgck/DuratorEmu#3]
I want to study how the game server is written. My World of Warcraft version is 1.12.1. There seems to be no way to connect. I have been in the authentication process, so I want to download a 1.1.2 client for testing.

**Comment by dece** [comment]
I won't post this publicly but if you can't find it on the web, provide me an email address and I'll help you out.

**Comment by ghost** [comment]
Thank you, my email address is fan3750060@163.com
