### ISSUE TITLE
works with BC or WoLK ?

### ISSUE THREAD

**Issue by pooyatavan** [Shgck/DuratorEmu#4]
is this source works with BC or WoLK ? or even posible ?

**Comment by Banamu** [comment]
@pooyatavan I found this project today and I am also interested in this. My python skills will definitely be tested  here so I will start to work on getting this up and running and seeing where it leads.

**Comment by pooyatavan** [comment]
did make it run this core ?
i don't know how to fired up  o_O.

**Comment by pooyatavan** [comment]
> @pooyatavan I found this project today and I am also interested in this. My python skills will definitely be tested here so I will start to work on getting this up and running and seeing where it leads.

just like me. did make it run this core ?
i don't know how to fired up o_O.

**Comment by Banamu** [comment]
Hello, I've been digging through code in the native 1.1.2 core as I noticed it was very early stages. (Only Undead Rogues work) so I've tasked myself with bringing it up a little more to life before trying to figure out authentication for BC / WOTLK. We can discuss about it on Discord

**Comment by pooyatavan** [comment]
sure my discord is Admiral#7162

**Comment by dece** [comment]
Hi, this server works pretty much only for 1.1.2 which is early vanilla, and won't work for later versions even vanilla, let alone expansions. There are a lot of more advanced and usable servers for both BC and LK.
